spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # model的包
  type-aliases-package: com.example.mybatisdemo.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    com.example.mybatisdemo.mapper : debug

isEnable: true
